Ft cloud post
zegetech/zegetech.github.io pull request #14
Opened 2018-11-14 02:45 UTC by Melvin1Atieno

### what this pr does
1. Adds a post on cloud and cloud computing.
### relevant links
[post](https://github.com/Melvin1Atieno/zegetech.github.io/blob/ft-cloud-post/_posts/2018-11-12-cloud-cloud-computing.md)

2018-11-15 14:53 UTC, zegetech requested changes
Draft review done. Cant wait to see version 2

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +
And mother asked, "what happens when it rains?"

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +
Please mention VPS, as that is waht is used mainly in marketing IaaS

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +Say you want a Linux based server. You will go to any of the above sites. Provision yourself a virtual machine and that's it. You can now deploy whatever application you want to the machine/server, i
virtual machine or VPS (virtual private server)

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +Examples Iaas providers include; [Digital Ocean](https://www.digitalocean.com/),[linode](https://www.linode.com/), [AWS](https://aws.amazon.com/),[vultr](https://www.vultr.com/).
add a few more popular ones like OVH and also aws it very wide, but their VPS service is called lightsail.

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +Example of Paas providers are [Heroku](https://www.heroku.com/), [Go daddy](https://uk.godaddy.com), etc
Heroku is clear but godaddy is confusing. Please link to the exact product that is a PaaS. Also mention BaaS as well as opensource solution for running PaaS. FIrebase is also an example. List others here as well.

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +A good example of a Software as a service is Gmail provided by Google.
Please list and link to other examples. Even our own product MPAYER isa SaaS. Look for a list over the internet of Popular SaaS products and mention that zegetech has great speciality in building SaaS products and we understand this very clearly.

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +
Also add Kubernetes and containerisatio infrastructure and where that fits into the cloud. is it IaaS, PaaS etc. THen give examples of providers

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +## Essential characteristics
Essential characteristics of what exactly. If refering to xters of cloud computing, then this should come first i should think, not at the bottom.

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +5. **Measured service.** Usage can be monitored, controlled, and reported, providing transparency for both the provider and consumer of the utilized service.
Need to add developing and testing cloud infrastructure on your local host. For IaaS, you'd look at vagrant, virtual box, vmware etc. For Kubernetes you'd look at rancher etc and for PaaS you'd look at flynn, dokku, deis.

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +Example of Paas providers are [Heroku](https://www.heroku.com/), [Go daddy](https://uk.godaddy.com), etc
Soem open source solution for PaaS are like flynn, dokku, deis etc. Please uncover all options.

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +Example of Paas providers are [Heroku](https://www.heroku.com/), [Go daddy](https://uk.godaddy.com), etc
Also please list top PaaS that are used to deploy rails application specifically.

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +
Your intros need to be bit longer to fit the listing formats.

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +
Make this post bit more lively. e. g look for a funny cartoon about cloud to put the point across. xkcd.com has a few nice ones. Remember, this is an informative post and not practical, so in needs to be very enlightening , engaging, interesting and fun

2018-11-15 14:53 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +Cloud services are delivered in a number of ways; Infrastructure as a service(IaaS), Platform as a service(PaaS) and Software as a service(SaaS). Here is a picture of resources you would traditionall
Mention XaaS got from here https://searchcloudcomputing.techtarget.com/definition/XaaS-anything-as-a-service. try incorporate this as well and see the major classes of XaaS.

2018-11-15 15:07 UTC, Melvin1Atieno commented
Noted.

2018-11-19 20:21 UTC, Melvin1Atieno commented
Version 2 is out.!!!

2018-11-20 08:56 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +Example of Paas providers are [Heroku](https://www.heroku.com/), [Go daddy](https://uk.godaddy.com), etc
Please include the open source options of PaaS as i had mentioned like flynn, dokku, deis

2018-11-20 08:57 UTC, zegetech commented on _posts/2018-11-12-cloud-cloud-computing.md
> +5. **Measured service.** Usage can be monitored, controlled, and reported, providing transparency for both the provider and consumer of the utilized service.
Please add this as well.

2018-11-20 08:58 UTC, zegetech commented
Please view the unresolved conversation and include the content.

2018-11-22 09:27 UTC, zegetech approved these changes

2018-11-22 09:27 UTC, merged