Blog - deploying a monolith rails application
zegetech/zegetech.github.io pull request #16
Opened 2018-11-15 14:07 UTC by NgariNdungu

[related file](https://github.com/NgariNdungu/zegetech.github.io/blob/d5dfbb0c4fa48c3b6c9240d6d4d76dae7f8c29d0/_posts/2018-11-13-deploy-rails.md)

2018-11-15 15:22 UTC, zegetech requested changes

2018-11-15 15:22 UTC, zegetech commented on _posts/2018-11-13-deploy-rails.md
> +
Mention somewhere that it is good practice not to wait till you application is done to deploy it, but to start with a deployed boilerplate, in rails case, deploying a rails new app, and making user the changes are also always deployed.. Also mention the need for staging, production and dev environments.

2018-11-15 15:22 UTC, zegetech commented on _posts/2018-11-13-deploy-rails.md
> +We have the choice of deploying our site to a PaaS provider such as [Heroku] or using a VPS from a IaaS provider.
Mention cloud and link to the article about cloud

2018-11-15 15:22 UTC, zegetech commented on _posts/2018-11-13-deploy-rails.md
> +The process of setting up is not much different from what you did to get the app running on your development machine.
Please mention the advantages over easier PaaS, like control over dependancies, services as well as huge cost savings and optimisation

2018-11-15 15:22 UTC, zegetech commented on _posts/2018-11-13-deploy-rails.md
> +## Our production environment
Again, mention as best practice, you need 2 to 3  environments for a real live system. development, staging(bleeding edge) and production(stable)

2018-11-15 15:22 UTC, zegetech commented on _posts/2018-11-13-deploy-rails.md
> +#### User Setup
Divide your sections into steps as this is a practical blog that you want devs to follow through

2018-11-15 15:22 UTC, zegetech commented on _posts/2018-11-13-deploy-rails.md
> +
add a relevant image to draw attention. also include the first steps that help people to get going with rails_seed.

2018-11-15 15:22 UTC, zegetech commented on _posts/2018-11-13-deploy-rails.md
> +
Mention that rails seed is an app template that we developed at zegetech

2018-11-15 15:22 UTC, zegetech commented on _posts/2018-11-13-deploy-rails.md
> +
Include "how to" of deploying rails seed on local without using a VPS in the cloud. Talking about vagrant and docker. So basically a step by step for how to use the template to deploy to a docker container or vagrant.

2018-11-20 09:35 UTC, NgariNdungu commented
I have made the requested changes. [Here's the updated post](https://github.com/NgariNdungu/zegetech.github.io/blob/feature-blog-deploy-monolith/_posts/2018-11-13-deploy-rails.md)

2018-11-20 09:59 UTC, zegetech requested changes

2018-11-20 09:59 UTC, zegetech commented on _posts/2018-11-13-deploy-rails.md
> +#### User Setup
Please use number that are easier to follow in addition to H1 H2 etc...

2018-11-20 09:59 UTC, zegetech commented on _posts/2018-11-13-deploy-rails.md
> +You can refer to [this article](https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-16-04) for an explanation and step-by-step.
deploy user or  user for deploying

2018-11-20 09:59 UTC, zegetech commented on _posts/2018-11-13-deploy-rails.md
> +This is referred as *User data* on digital ocean while aws lightsail asks for a *launch script*. Here's an [example script](https://github.com/kgathi2/rails_seed#vps-preparation).
Mention cloud_init which user data works of off.

2018-11-20 09:59 UTC, zegetech commented on _posts/2018-11-13-deploy-rails.md
> +
Add how to set up ssh key on local host for ssh authentication without password

2018-11-23 07:44 UTC, zegetech approved these changes

2018-11-23 07:45 UTC, merged